### PR TITLE
Update manifest for samples according to spec

### PR DESCRIPTION
**Pull request by wang16**
Following http://w3c.github.io/manifest/ with
xwalk's vendor extensions.

Related BUG: XWALK-2591

### CODE REVIEW

**Comment by wang16** [comment]
@baleboy , I'm not sure who should ping for demos' review.

**Comment by halton** [comment]
I think peer review is also okay. You have my lgtm.

**Comment by wang16** [comment]
OK, neither of the two owners in OWNERS is working on crosswalk now. I will merge this one.

**Comment by baleboy** [comment]
@kenchris is right, please follow https://crosswalk-project.org/documentation/manifest.html

**Pull request merged**
