### PR TITLE
Update manifest.json to support app tools

### PR DESCRIPTION
**Pull request by haoxli**
- Add xwalk_package_id  in manifest
- Update version, icon in manifest

https://crosswalk-project.org/jira/browse/XWALK-5737

### CODE REVIEW

**Comment by davidmaxwaterman** [comment]
I'm not sure how much say I have in this, but I'd prefer these changes to be made upstream :

https://github.com/01org/webapps-hangonman
https://github.com/01org/webapps-memory-game-older-kids

Also, why does one have a key field, and the other not? ...and one has 'start_url' as 'app/index.html' and the other is simply 'index.html'. That doesn't seem quite right to me - they should be the same, iinm.

I'm not too keen on a different 'package_id' to their upstream ones either.

Can you tell me what the motivation is behind these changes?

**Comment by haoxli** [comment]
hi @davidmaxwaterman crosswalk will replace make_apk.py with app tools, the app tools need a package id in manifest.json.
I don't update the upstream code because this changes of manifest.json align to app tools requirement. I see that there is single manifest.json in each demo, so update it.

**Comment by davidmaxwaterman** [comment]
Ok, fair enough - it's quite a bit more work to switch the upstream to use app tools, but I have it on my todo list.

What about the other questions I had...why are the changes not 'the same'? Ie one has 'app/index.html' vs 'index.html' and one has a 'key' but the other not?

**Comment by haoxli** [comment]
I just update the existed items in the manifest.json, and remove not support/useless items. I do not clear whether the "key" in MemoryGame/manifest.json have special use, so keep it.
I have updated "index.html" to "app/index.html".

**Comment by davidmaxwaterman** [comment]
OK, thanks for app/index.html change.

From the diff, it still looks like you've added the key...is that not the case?

**Comment by haoxli** [comment]
Oh sorry, I diff a incorrect version of manifest.json, not notice that the origin repo has not this key. It may be added in our local test code by manual, I will remove it soon.

**Comment by davidmaxwaterman** [comment]
lgtm

**Pull request merged**
