### PR TITLE
Deprecate demo for Device Capabilities

### PR DESCRIPTION
**Pull request by zqzhang**
The checkpoints of this demo has been covered by demo-express at
https://github.com/crosswalk-project/demo-express/blob/master/samples/DeviceCapabilities/index.html

The demo-express has been documented at
https://crosswalk-project.org/documentation/samples/demoexpress.html
and released to Google Play.

### CODE REVIEW

**Comment by zqzhang** [comment]
I am volunteering to revisit the applications in this repository to see if they are valuable for [crosswalk-samples](https://github.com/crosswalk-project/crosswalk-samples) or [demo-express](https://github.com/crosswalk-project/demo-express). And target for deprecating this repository because it is very confusable for application developers with crosswalk-samples and crosswalk-demos.

@rakuco @baleboy PTAL, thanks.

CC @haoxli @jennycao

**Comment by davidmaxwaterman** [comment]
sounds fine to me...am I expected to review/merge these PRs? I'm happy to, but if there's someone more appropriate...
let me know.

**Comment by zqzhang** [comment]
@davidmaxwaterman feel free to review/merge PRs.

By the way, are you still working on / maintaining the web apps at https://01.org/html5webapps/webapps? @Honry and I think it is valuable for enabling those applications with Crosswalk Project, but we need to revisit them and to make them workable with latest Crosswalk binaries. What do you say?

**Comment by Honry** [comment]
@zqzhang, agree! Those are all very interesting samples and it is a good way to spread Crosswalk.

**Comment by davidmaxwaterman** [comment]
OK, thanks.

Yes, I still maintain the html5 web apps. There are quite many of them (20?), so they don't all get the love and attention that they could use.

I added a new one (Content Push) recently, but it's not applicable to crosswalk, and I'm currently working on that one.

I also worked briefly with @r0b5t4 (Robert Staudinger) on the new crosswalk-app-tools using Annex to test how they work.
I haven't done any actual changes to reflect that, but it shouldn't be too difficult. I was hoping to change 'grunt-crosswalk' to wrap the crosswalk-app-tools so they can be used in the same way as the current version, but I've not done anything about that yet. However, one outcome was that Annex (at least) does still work with the latest crosswalk, so I don't think there's much to do to get them to work - it's mostly about switching the tooling.

Note that those apps don't just run on crosswalk, so they do need to be built (as per instructions). Once built, then you can use the crosswalk-app-tools to package them.

If you want to take a shot at that, then please do...all apps are open and PRs are welcome, and I have had the occasional PR to fix this-and-that :) Some people have even copied them into their own products, which is nice :)

Regards,

Max.

**Comment by zqzhang** [comment]
> I also worked briefly with @r0b5t4 (Robert Staudinger) on the new crosswalk-app-tools using Annex to test how they work.

Great!

@Honry has been working on the crosswalk-app-tools testing. Maybe he is interested in the tools switching.

**Comment by Honry** [comment]
@zqzhang, @davidmaxwaterman, I would like to contribute, let's keep in touch. :smile:

**Pull request merged**
